function result = boosted_detector(image, scales, classifiers, ...
                                   weak_classifiers, face_size, ...
                                   result_number)

% function result = boosted_detector(image, scales, classifiers, ...
%                                    weak_classifiers, face_size, ...
%                                    result_number)
%
% first, find_faces identifies, for every position in the image, the 
% scale that maximizes the normalized correlation with the
% average face. Then, the top results are re-ranked based on how well they
% match the top eigenfaces.

[max_responses, max_scales] = ...
    boosted_multiscale_search(image, scales, classifiers, ...
                              weak_classifiers, face_size, result_number);

result = detection_boxes(image, zeros(face_size), max_responses, ...
                         max_scales, result_number);